'use client';

import React from 'react';
import page from '@/components/page';
import HeroSection from '@/components/HeroSection';
import AboutSection from '@/components/AboutSection';
import ServicesSection from '@/components/ServicesSection';
import MembershipPlansSection from '@/components/MembershipPlansSection';
import TrainersSection from '@/components/TrainersSection';

export default function HomePage() {
  return (
    <div className="flex min-h-screen flex-col">
      <main className="flex-1 container mx-auto px-4 py-8">
        {/* Components generated by the builder will be added here */}
      
        <page />
      
        <HeroSection />
        <AboutSection />
        <ServicesSection />
        <MembershipPlansSection />
        <TrainersSection />
      </main>
      
      <footer className="py-6 bg-gray-100 dark:bg-gray-800">
        <div className="container mx-auto px-4 text-center text-gray-500 text-sm">
          &copy; 2025 מכון כושר גמא. webis
        </div>
      </footer>
    </div>
  );
}